FROM node:24-alpine
LABEL authors="Emmett Willis"

# Set the working directory
WORKDIR /app

ENV NG_CLI_ANALYTICS=false

# Install Angular CLI
RUN npm install -g @angular/cli

# Expose the application port
EXPOSE 4200
